version: '3.8'
services:
  fhirdb:
    image: healthsamurai/fhir-db:latest
    container_name: fhirdb
    ports:
      - "8080:8080"
    environment:
      - FHIR_DB_USER=admin
      - FHIR_DB_PASSWORD=admin
      - FHIR_DB_URL=http://fhirdb:8080
    volumes:
      - fhir-db-data:/var/lib/fhir-db
    networks:
      - health-network

  fhirbase:
    image: fhirbase/fhirbase:latest
    container_name: fhirbase
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=fhirbase
      - POSTGRES_PASSWORD=fhirbase
      - POSTGRES_DB=fhirbase
    volumes:
      - fhirbase-data:/var/lib/postgresql/data
    networks:
      - health-network

  postgres-jwt:
    image: postgres:15-alpine
    container_name: postgres-jwt
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=Testpdaw
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - health-network

  springboot-app:
    build: .
    container_name: springboot-app
    ports:
      - "8086:8086"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-jwt:5432/Testpdaw
      - FHIRBASE_URL=http://fhirbase:8080/fhir
      - HEALTHSAMURAI_URL=http://fhirdb:8080/fhir
      - JWT_SECRET=${JWT_SECRET}
    depends_on:
      - fhirbase
      - fhirdb
      - postgres-jwt
    networks:
      - health-network

volumes:
  fhir-db-data:
  fhirbase-data:
  pgdata:

networks:
  health-network:
    driver: bridge
