services:
  postgres-jwt:
    image: postgres:latest
    container_name: postgres-jwt
    restart: always
    environment:
      POSTGRES_DB: Testpdaw
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: Mm29Juanito
      POSTGRES_INITDB_ARGS: --auth-host=md5
    ports:
      - "5432:5432"
    networks:
      - health-network
    volumes:
      - pgjwt-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fhirbase-db:
    image: postgres:latest
    container_name: fhirbase-db
    restart: always
    environment:
      POSTGRES_DB: fb
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: fhirpassword
      POSTGRES_INITDB_ARGS: --auth-host=md5
    ports:
      - "5433:5432"
    networks:
      - health-network
    volumes:
      - fhirbase-data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  fhirbase:
    image: fhirbase/fhirbase:latest
    container_name: fhirbase
    restart: always
    depends_on:
      fhirbase-db:
        condition: service_healthy
    environment:
      DATABASE_URL: postgres://postgres:fhirpassword@fhirbase-db:5432/fb
      PGHOST: fhirbase-db
      PGPORT: 5432
      PGDATABASE: fb
      PGUSER: postgres
      PGPASSWORD: fhirpassword
    ports:
      - "3000:3000"
    networks:
      - health-network
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/fhir"]
      interval: 10s
      timeout: 5s
      retries: 5

  myobservation:
    build: .
    container_name: myobservation
    restart: always
    depends_on:
      postgres-jwt:
        condition: service_healthy
      fhirbase:
        condition: service_healthy
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres-jwt:5432/Testpdaw
      SPRING_DATASOURCE_USERNAME: postgres
      SPRING_DATASOURCE_PASSWORD: Mm29Juanito
      FHIR_DATASOURCE_URL: jdbc:postgresql://fhirbase-db:5432/fb
      FHIR_DATASOURCE_USERNAME: postgres
      FHIR_DATASOURCE_PASSWORD: fhirpassword
      FHIRBASE_URL: http://fhirbase:3000/fhir
    ports:
      - "8085:8085"
    networks:
      - health-network

networks:
  health-network:
    driver: bridge

volumes:
  pgjwt-data:
  fhirbase-data: