@startuml

/' diagram meta data start
config=StructureConfiguration;
{
  "projectClassification": {
    "searchMode": "OpenProject", // OpenProject, AllProjects
    "includedProjects": "",
    "pathEndKeywords": "*.impl",
    "isClientPath": "",
    "isClientName": "",
    "isTestPath": "",
    "isTestName": "",
    "isMappingPath": "",
    "isMappingName": "",
    "isDataAccessPath": "",
    "isDataAccessName": "",
    "isDataStructurePath": "",
    "isDataStructureName": "",
    "isInterfaceStructuresPath": "",
    "isInterfaceStructuresName": "",
    "isEntryPointPath": "",
    "isEntryPointName": "",
    "treatFinalFieldsAsMandatory": false
  },
  "graphRestriction": {
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "removeByInheritance": "", // inheritance/annotation based filtering is done in a second step
    "removeByAnnotation": "",
    "removeByClassPackage": "", // cleanup the graph after inheritance/annotation based filtering is done
    "removeByClassName": "",
    "cutMappings": false,
    "cutEnum": true,
    "cutTests": true,
    "cutClient": true,
    "cutDataAccess": false,
    "cutInterfaceStructures": false,
    "cutDataStructures": false,
    "cutGetterAndSetter": true,
    "cutConstructors": true
  },
  "graphTraversal": {
    "forwardDepth": 6,
    "backwardDepth": 6,
    "classPackageExcludeFilter": "",
    "classPackageIncludeFilter": "",
    "classNameExcludeFilter": "",
    "classNameIncludeFilter": "",
    "methodNameExcludeFilter": "",
    "methodNameIncludeFilter": "",
    "hideMappings": false,
    "hideDataStructures": false,
    "hidePrivateMethods": true,
    "hideInterfaceCalls": true, // indirection: implementation -> interface (is hidden) -> implementation
    "onlyShowApplicationEntryPoints": false, // root node is included
    "useMethodCallsForStructureDiagram": "ForwardOnly" // ForwardOnly, BothDirections, No
  },
  "details": {
    "aggregation": "GroupByClass", // ByClass, GroupByClass, None
    "showClassGenericTypes": true,
    "showMethods": true,
    "showMethodParameterNames": true,
    "showMethodParameterTypes": true,
    "showMethodReturnType": true,
    "showPackageLevels": 2,
    "showDetailedClassStructure": true
  },
  "rootClass": "com.myobservation.fhir.controller.FhirPractitionerController",
  "extensionCallbackMethod": "" // qualified.class.name#methodName - signature: public static String method(String)
}
diagram meta data end '/



digraph g {
    rankdir="TB"
    splines=polyline
    

'nodes 
subgraph cluster_940295936 { 
   	label=myobservation
	labeljust=l
	fillcolor="#ececec"
	style=filled
   
   subgraph cluster_1376730215 { 
   	label=fhir
	labeljust=l
	fillcolor="#d8d8d8"
	style=filled
   
   FhirPractitionerController892914332[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FhirPractitionerController</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   practitionerService: FhirPractitionerService [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ createPractitioner(practitionerJson: String, userId: Long): ResponseEntity&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ deletePractitioner(id: Long): ResponseEntity&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getPractitionerById(id: Long): ResponseEntity&lt;String&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ updatePractitioner(id: Long, practitionerJson: String): ResponseEntity&lt;String&gt;</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];

FhirPractitionerService1642493459[
	label=<<TABLE BORDER="1" CELLBORDER="0" CELLPADDING="4" CELLSPACING="0">
<TR><TD ALIGN="LEFT" >(C)FhirPractitionerService</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >-   fhirContext: FhirContext [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   fhirValidator: FhirValidator [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   jsonParser: IParser [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   myUserRepository: MyUserRepository [0..1]</TD></TR>
<TR><TD ALIGN="LEFT" >-   practitionerRepository: FhirPractitionerRepository [0..1]</TD></TR>
<HR/>
<TR><TD ALIGN="LEFT" >+ deleteById(id: Long)</TD></TR>
<TR><TD ALIGN="LEFT" >+ findAll(): List&lt;FhirPractitionerEntity&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ findById(id: Long): Optional&lt;FhirPractitionerEntity&gt;</TD></TR>
<TR><TD ALIGN="LEFT" >+ getById(id: Long): Practitioner</TD></TR>
<TR><TD ALIGN="LEFT" >+ save(practitionerJson: String, userId: Long): FhirPractitionerEntity</TD></TR>
<TR><TD ALIGN="LEFT" >+ update(id: Long, practitionerJson: String): FhirPractitionerEntity</TD></TR>
</TABLE>>
	style=filled
	margin=0
	shape=plaintext
	fillcolor="#FFFFFF"
];
} 
} 

'edges    
FhirPractitionerController892914332 -> FhirPractitionerService1642493459[label="practitionerService
[0..1]"];
    
}
@enduml